spring:
  application:
    name: umc10th

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    # ddl-auto: 개발 단계에선 update, 운영 단계에선 validate 권장
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # SQL 주석을 보여줘서 어떤 쿼리인지 파악하기 쉽게 함
        highlight_sql: true    # 콘솔에서 SQL 키워드에 색상을 입힘 (Spring Boot 3.x 이상)

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_REST_API_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth/callback/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 1800000 # 30분